// Temporary mock AI implementation so you can keep developing
// without needing a working OpenAI key.

import { serverEnv } from "@/lib/validation/env";

type GenerateCampaignArgs = {
  productOrOffer: string;
  channel: "email" | "whatsapp";
};

export type GeneratedCampaignContent = {
  subject: string;
  body: string;
};

export async function generateCampaignContent({
  productOrOffer,
  channel,
}: GenerateCampaignArgs): Promise<GeneratedCampaignContent> {
  // Simple deterministic "AI" for development
  const short = productOrOffer.slice(0, 60);

  const subject =
    channel === "email"
      ? `Special offer: ${short}`
      : `WhatsApp offer: ${short}`;

  const body =
    `Hi there,\n\n` +
    `Here is a mock ${channel} campaign for:\n` +
    `"${productOrOffer}".\n\n` +
    `In a real environment, this would be generated by ${serverEnv.OPENAI_MODEL}.\n` +
    `You can customize this message before sending.\n\n` +
    `Best,\nOmniMarketing`;

  return { subject, body };
}



// import OpenAI from "openai";
// import { serverEnv } from "@/lib/validation/env";

// const openai = new OpenAI({
//   apiKey: serverEnv.OPENAI_API_KEY,
// });

// type GenerateCampaignArgs = {
//   productOrOffer: string;
//   channel: "email" | "whatsapp";
// };

// export type GeneratedCampaignContent = {
//   subject: string;
//   body: string;
// };

// export async function generateCampaignContent({
//   productOrOffer,
//   channel,
// }: GenerateCampaignArgs): Promise<GeneratedCampaignContent> {
//   const model = serverEnv.OPENAI_MODEL;

//   const prompt = `
// You are an expert ${channel} marketing copywriter.

// Write a short campaign for:
// ${productOrOffer}

// Return a JSON object with exactly this shape:
// {
//   "subject": "...",
//   "body": "..."
// }
// - "subject": a concise, compelling line (max ~80 chars)
// - "body": plain text message (2–4 short paragraphs, no markdown)
// `;

//   const response = await openai.chat.completions.create({
//     model,
//     messages: [
//       {
//         role: "system",
//         content:
//           "You are a helpful marketing assistant. Always respond with valid JSON only.",
//       },
//       {
//         role: "user",
//         content: prompt,
//       },
//     ],
//     temperature: 0.7,
//   });

//   const content = response.choices[0]?.message?.content;

//   if (!content) {
//     throw new Error("OpenAI returned no content");
//   }

//   // Try to parse JSON from the response
//   try {
//     const parsed = JSON.parse(content) as GeneratedCampaignContent;

//     if (!parsed.subject || !parsed.body) {
//       throw new Error("Missing subject or body in AI response");
//     }

//     return parsed;
//   } catch (err) {
//     console.error("Failed to parse AI response:", content);
//     throw new Error("AI response was not valid JSON");
//   }
// }